# Generated by Django 3.2.4 on 2021-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('itemdescription', models.TextField(max_length=200)),
                ('itemdescriptionmain', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
